// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibrary(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddLibrary'](arg1, arg2, arg3);
}

export function BrowseFileSystem(arg1) {
  return window['go']['main']['App']['BrowseFileSystem'](arg1);
}

export function BulkRenameMovies(arg1) {
  return window['go']['main']['App']['BulkRenameMovies'](arg1);
}

export function BulkScrapeMovies(arg1) {
  return window['go']['main']['App']['BulkScrapeMovies'](arg1);
}

export function BulkScrapeTVShows(arg1) {
  return window['go']['main']['App']['BulkScrapeTVShows'](arg1);
}

export function CleanupLibrary(arg1) {
  return window['go']['main']['App']['CleanupLibrary'](arg1);
}

export function DeleteArtwork(arg1, arg2) {
  return window['go']['main']['App']['DeleteArtwork'](arg1, arg2);
}

export function DeleteLibrary(arg1) {
  return window['go']['main']['App']['DeleteLibrary'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DownloadMedia(arg1, arg2) {
  return window['go']['main']['App']['DownloadMedia'](arg1, arg2);
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function ExportHTML() {
  return window['go']['main']['App']['ExportHTML']();
}

export function GenerateMovieNFO(arg1) {
  return window['go']['main']['App']['GenerateMovieNFO'](arg1);
}

export function GenerateTVShowNFO(arg1) {
  return window['go']['main']['App']['GenerateTVShowNFO'](arg1);
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetLibraries() {
  return window['go']['main']['App']['GetLibraries']();
}

export function GetLocalArtwork(arg1) {
  return window['go']['main']['App']['GetLocalArtwork'](arg1);
}

export function GetMovieDetails(arg1) {
  return window['go']['main']['App']['GetMovieDetails'](arg1);
}

export function GetMovies() {
  return window['go']['main']['App']['GetMovies']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTVShowDetails(arg1) {
  return window['go']['main']['App']['GetTVShowDetails'](arg1);
}

export function GetTVShows() {
  return window['go']['main']['App']['GetTVShows']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function ListArtwork(arg1) {
  return window['go']['main']['App']['ListArtwork'](arg1);
}

export function MatchMovie(arg1, arg2) {
  return window['go']['main']['App']['MatchMovie'](arg1, arg2);
}

export function MatchTVShow(arg1, arg2) {
  return window['go']['main']['App']['MatchTVShow'](arg1, arg2);
}

export function OpenInPlayer(arg1) {
  return window['go']['main']['App']['OpenInPlayer'](arg1);
}

export function PatchSettings(arg1) {
  return window['go']['main']['App']['PatchSettings'](arg1);
}

export function PickAndUploadArtwork(arg1, arg2) {
  return window['go']['main']['App']['PickAndUploadArtwork'](arg1, arg2);
}

export function PlayEpisode(arg1) {
  return window['go']['main']['App']['PlayEpisode'](arg1);
}

export function PlayMovie(arg1) {
  return window['go']['main']['App']['PlayMovie'](arg1);
}

export function RenameMovie(arg1) {
  return window['go']['main']['App']['RenameMovie'](arg1);
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}

export function SearchExternalMovie(arg1, arg2) {
  return window['go']['main']['App']['SearchExternalMovie'](arg1, arg2);
}

export function SearchExternalTV(arg1, arg2) {
  return window['go']['main']['App']['SearchExternalTV'](arg1, arg2);
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function TriggerScrape(arg1) {
  return window['go']['main']['App']['TriggerScrape'](arg1);
}

export function TriggerTVScrape(arg1) {
  return window['go']['main']['App']['TriggerTVScrape'](arg1);
}

export function UpdateLibrary(arg1, arg2) {
  return window['go']['main']['App']['UpdateLibrary'](arg1, arg2);
}

export function UpdateMovie(arg1, arg2) {
  return window['go']['main']['App']['UpdateMovie'](arg1, arg2);
}

export function UpdateTVShow(arg1, arg2) {
  return window['go']['main']['App']['UpdateTVShow'](arg1, arg2);
}
