// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {services} from '../models';

export function AddLibrary(arg1:string,arg2:string,arg3:string):Promise<models.Library>;

export function BrowseFileSystem(arg1:string):Promise<main.FileSystemNode>;

export function BulkRenameMovies(arg1:Array<number>):Promise<string>;

export function BulkScrapeMovies(arg1:Array<number>):Promise<string>;

export function BulkScrapeTVShows(arg1:Array<number>):Promise<string>;

export function CleanupLibrary(arg1:number):Promise<Record<string, any>>;

export function DeleteArtwork(arg1:number,arg2:string):Promise<boolean>;

export function DeleteLibrary(arg1:number):Promise<boolean>;

export function DeleteTask(arg1:string):Promise<boolean>;

export function DownloadMedia(arg1:string,arg2:number):Promise<string>;

export function ExportCSV():Promise<string>;

export function ExportHTML():Promise<string>;

export function GenerateMovieNFO(arg1:number):Promise<boolean>;

export function GenerateTVShowNFO(arg1:number):Promise<boolean>;

export function GetDrives():Promise<Array<main.Drive>>;

export function GetLibraries():Promise<Array<models.Library>>;

export function GetLocalArtwork(arg1:string):Promise<string>;

export function GetMovieDetails(arg1:number):Promise<models.Movie>;

export function GetMovies():Promise<Array<models.Movie>>;

export function GetSettings():Promise<Record<string, any>>;

export function GetTVShowDetails(arg1:number):Promise<models.TVShow>;

export function GetTVShows():Promise<Array<models.TVShow>>;

export function GetTasks():Promise<Array<models.BackgroundTask>>;

export function ListArtwork(arg1:number):Promise<Array<services.ArtworkInfo>>;

export function MatchMovie(arg1:number,arg2:string):Promise<boolean>;

export function MatchTVShow(arg1:number,arg2:string):Promise<boolean>;

export function OpenInPlayer(arg1:string):Promise<void>;

export function PatchSettings(arg1:Record<string, any>):Promise<Record<string, any>>;

export function PickAndUploadArtwork(arg1:number,arg2:string):Promise<string>;

export function PlayEpisode(arg1:number):Promise<void>;

export function PlayMovie(arg1:number):Promise<void>;

export function RenameMovie(arg1:number):Promise<Record<string, any>>;

export function ScanLibrary(arg1:number):Promise<string>;

export function SearchExternalMovie(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function SearchExternalTV(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function ShowInFolder(arg1:string):Promise<void>;

export function TriggerScrape(arg1:number):Promise<string>;

export function TriggerTVScrape(arg1:number):Promise<string>;

export function UpdateLibrary(arg1:number,arg2:Record<string, any>):Promise<models.Library>;

export function UpdateMovie(arg1:number,arg2:Record<string, any>):Promise<models.Movie>;

export function UpdateTVShow(arg1:number,arg2:Record<string, any>):Promise<models.TVShow>;
